### ISSUE TITLE
Defect 13 - changed title

### ISSUE THREAD

**Issue by FrankStraif** [Verigreen/agm-github-test#128]
<p>Test from AgM with user Frank</p>

**Comment by agm-github-integration-service** [comment]
<span style="color:#000080;font-family:'arial'"><span style="font-size:8pt"><strong> Frank Straif &lt;frank.straif@hp.com&gt;, Nov-18-2015:</strong></span></span> 

<p>agmComment</p>

**Comment by FrankStraif** [comment]
comment from Github

**Comment by agm-github-integration-service** [comment]
<span style="color:#000080;font-family:'arial'"><span style="font-size:8pt"><strong> Frank Straif &lt;frank.straif@hp.com&gt;, Nov-20-2015:</strong></span></span> 

<p>test friday</p>
